POST http://localhost:8000/api/asesoria HTTP/1.1
Accept: application/application/json
Content-Type: : application/json

{
    "oferta_fecha":"2010-10-10",
    "oferta_tarifa": "100",
    "materia_id":"2",
    "estudiante_id":"3" 
}