POST http://localhost:8000/api/pregunta HTTP/1.1
Accept: application/json
Content-Type: : application/json

{
    "administrador_id": 1,
    "pregunta_pregunta": "salv",
    "pregunta_respuesta": "salv",
}